app:
  image: ibmcom/swift-ubuntu:4.0.2
  volumes:
    - .:/Kitura-Session-Redis
  command: bash -c "cd /Kitura-Session-Redis  && swift package --build-path .build-ubuntu clean && swift build --build-path .build-ubuntu && swift test --build-path .build-ubuntu"
